reverence/main/urls.py
from .views import CatalogView, ClothingItenDetailView
from django.urls import path


app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name='catalog'),
    path('item/<slug:slug>/', ClothingItenDetailView.as_view(),
         name='clothing_item_detail')
]

reverence/reverence/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

reverence/main/models.py
from django.db import models


class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name
    


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)


    def __str__(self):
        return self.name
    

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class ClothingItem(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    available = models.BooleanField(default=True)
    sizes = models.ManyToManyField('Size', through='ClothingItemSize',
                                   related_name='clothing_item', blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE,
                                 related_name='clothing_items')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=5, decimal_places=2)


    def __str__(self):
        return self.name
    
    def get_price_with_discount(self):
        if self.discount > 0:
            return self.price * (1 - (self.discount / 100))
        return self.price
    


class ClothingItemSize(models.Model):
    clothing_item = models.ForeignKey(ClothingItem, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)


    class Meta:
        unique_together = ('clothing_item', 'size')

    

    

reverence/main/views.py
from django.views.generic import ListView, DeleteView
from .models import ClothingItem, Category, Size
from django.db.models import Q
from typing import Any, Dict


class CatalogView(ListView):
    model = ClothingItem
    template_name = 'main/product/list.html'
    context_object_name = 'cloting_items'

    
    def get_queryset(self):
        queryset = super().get_queryset()
        category_slugs = self.request.GET.getlist('category')
        size_names = self.request.GET.getlist('size')
        min_price = self.request.GET.getlist('min_price')
        max_price = self.request.GET.getlist('max_price')

        if category_slugs:
            queryset = queryset.filter(category_slug__in=category_slugs)

        if size_names:
            queryset = queryset.filter(
                Q(sizes_name_in=size_names) & Q(sizes__clothingitemsize__available=True)
            )

        if min_price:
            queryset = queryset.filter(price__gte=min_price)

        if max_price:
            queryset = queryset.filter(price__gte=max_price)

        return queryset
    

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all() 
        context["sizes"] = Size.objects.all() 
        context["selected_categories"] = self.request.GET.getlist('category')
        context["selected_sizes"] = self.request.GET.getlist('size')
        context["min_price"] = self.request.GET.getlist('min_price', '')
        context["max_price"] = self.request.GET.getlist('max_price', '')

        return context
    

class ClothingItenDetailView(DeleteView):
    model = ClothingItem
    template_name = 'main/product/detail.html'
    context_object_name = 'clothing_item'
    slug_field = 'slug'
    slug_url_kwargs = 'slug'

    
    



        
    

reverence/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>


<html>
<head>
    <title>{% block title %}{%endblock title %}</title>

    {% comment %} bootstrap {% {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    {% comment%} css {% endcomment %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>
<body>
    <header class="header sticky-top d-flex align-items-center">
        <div class="header-logo">
            <img src="{% static 'img/rev.png' %}" alt="">
        </div>
        <div class="search">
            <form action="" id="search_form" class="search_form" style="display: none;">
                <input type="text" name='q' class="form_input" placeholder="Search">
                <button type="submit" class="btnforsearch"></button>
            </form>
        </div>
        <div class="header-nav d-flex gap-4">
            <a href="#" class="h-profile">
                <img src="{% static 'img/profile.png' %}" alt="">
            </a>
            <a href="#" class="h-profile">
                <img src="{% static 'img/cart.png' %}" alt="">
            </a>
            <div class="forsearh">
                <a href="#" id="toggle-search" class="toggle-search">
                    <img src="{% static 'img/search.png' %}" alt="">
                </a>
                <div class="search-popup" id="search-popup" style="display: none;">
                    <form class="search-form" method="get" action="" id="search-form">
                        <div class="input-container">
                            <input type="text" class="from_input" name='q' placeholder="Search">
                            <button type="submit" class="btnforsearch"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        {% block content %}{% endblock content %} 
    </div>

    <script>
        document.getElementById('toggle-search').addEventListener('click', function(event) {
            event.preventDefault();
            const searhPopup = document.getElementById('search-popup');

            if (searhPopup.style.display === 'none' || searhPopup.style.display === '') {
                searhPopup.style.display = 'block'
            } else {
                searhPopup.style.display = 'none';
            }
        })
    </script>

    {% comment %} for bootstrap {% endcomment %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js'%}"></script>
</body>
</html>

reverence/main/templates/main/product/detail.html
{% url 'main:catalog' %}

reverence/main/templates/main/product/list.html
{% extends "../base.html" %} 
{% load static %}
{% block title %}Reverence{% endblock title%}

{% block content%}
    <h1 class="rev-head text-uppercase" id="reverence-title">Reverence interlude - ALL</h1>
    <div class="catalog d-flex">
        <form action="{% url "main:catalog" %}" method="get" class="sidebar" id="filter-form">
            <h4 class="price-head">Price Range</h4>
            <div class="price-range">
                <input type="number" name="min_price" id="min_price" placeholder="Min Price" value="{{ request.get.min_price }}" oninput="">
                <input type="number" name="max_price" id="max_price" placeholder="Max Price" value="{{ request.get.max_price }}" oninput="">
            </div>

            <h4 class="category-head">Category:</h4>
            {% for category in categories %}
                <div class="category-option">
                    <input type="checkbox" name="category" id="category-{{ category.slug }}" value="{{ category.slug }}"
                    {% if category.slug in selected_categories %}checked{% endif %} onchange="">
                    <label for="category-{{ category.slug }}" class="d-flex">
                        <div class="category-name">{{ category.name }}</div> <div class="category-len">{{ category.get_item_count }}</div>
                    </label>
                </div>
            {% endfor %}

            <h4 class="size-head">Size:</h4>
            {% for size in sizes %}
                <div class="category-option">
                    <input type="checkbox" name="size" id="size-{{ size..name }}" value="{{ size.name }}"
                    {% if size.name in seleted_sizes %}checked{% endif %} onchange="">
                    <label for="size-{{ size.name }}">{{ size.name }}</label>
                </div>
            {% endfor %}
        </form>

        <div class="product-list">
            <div class="cart-container d-flex flex-wrap">
                {% for item in clothing_items %}
                    <div class="card">
                        {% if item.image %}
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="product-image">
                        {% endif %}
                        <div class="card-info">
                            <h5>{{ item.name }}</h5>
                            <p>${{ item.get_price_with_discount }}</p>
                        </div>
                    </div>

                {% empty %}
                    <p>No products.</p>
                {% endfor %}

            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const checkbox = document.querySelectorAll('.category-option input[type="checkbox"]');
            const form = document.getElementById('filter-form')

            checkbox.forEach(checkbox => {
                checkbox.addEventListener('change', function() {
                    form.submit();
                });
            });
        });

        let timeout;
        function debponceApplyFilters() {
            clearTimeout(timeout);
            timeout = setTimeout(() => {
                const form = document.getElementById('filter-form');
                form.submit();
            }, 1000);
        }

        function applyFilters() {
            const form = document.getElementById('filter-form');
            form.submit();
            updateTitle();
        }

        function updateTitle() {
            const checkbox = document.querySelectorAll('input[name = "category"]:checked');
            const = titleElement = document.getElementById('reverence-title');

            if (checkboxes.lenght > 0) {
                const selectedCategories = Array.form(checkboxes).map(checkbox => {
                    const categoryText = checkbox.nextElementsSibling.textContent.trim();
                    return categoryText;
                });
                titleElement.textContent = `REVERENCE INTELUDE = ${selectedCategories.join(', ')}`;
            } else {
                titleElement.textContent = 'REVERENCE INTELUDE - ALL';
            }
        }

        document.addEventListener("DOMContentLoaded", updateTitle);

        document.getElementById('')

    </script>
{% endblock content%}